var CrossViewJS=window.CrossViewJS={};window.console||(console={});console.log=console.log||function(){};console.warn=console.warn||function(){};console.error=console.error||function(){};console.info=console.info||function(){};
(function(a){if(!a)throw"jQuery not found!";a.extend(CrossViewJS,{options:{relativePath:null,ajaxDefaults:{cache:!1},link:{autoRegister:"crossview-mapping",view:"crossview-view"}},notifyError:function(a,e){a.addClass("crossview-error");a.attr("data-crossview-error",e);if(!e)throw"Exception not provided";console.error(e.stack||e)},clearError:function(a){a.removeClass("crossview-error");a.attr("data-crossview-error",null)},getAbsoluteURL:function(a){return!this.options.relativePath||0<=a.indexOf("://")||
"/"==a.charAt(0)?a:this.options.relativePath+a},traverseJSON:function(a,e){if(e)for(var e=e.split("."),c=0;c<e.length;c++)a=a[e[c]];return a},setRelativePath:function(a){this.options.relativePath="/"==a.charAt(a.length-1)?a:a+"/"},init:function(b){a.extend(!0,CrossViewJS.options,b);b.relativePath&&CrossViewJS.setRelativePath(b.relativePath)},fn:{}});a.crossview=function(b){if(CrossViewJS[b])return CrossViewJS[b].apply(this,Array.prototype.slice.call(arguments,1));if("object"===typeof b||!b)return CrossViewJS.init.apply(this,
arguments);a.error("Method "+b+" does not exist on jQuery.fn.crossview")};a.fn.crossview=function(b){if(CrossViewJS.fn[b])return CrossViewJS.fn[b].apply(this,Array.prototype.slice.call(arguments,1));if("object"===typeof b||!b)return CrossViewJS.init.apply(this,arguments);a.error("Method "+b+" does not exist on jQuery.crossview")};if(!a.fn.serializeObject)a.fn.serializeObject=function(){var b={},e=this.serializeArray();a.each(e,function(){void 0!==b[this.name]?(b[this.name].push||(b[this.name]=[b[this.name]]),
b[this.name].push(this.value||"")):b[this.name]=this.value||""});return b}})(jQuery);
(function(a){CrossViewJS.loadingMapping=0;a(function(){a("link[rel='"+CrossViewJS.options.link.autoRegister+"']").each(function(){var b=a(this).attr("href");console.log("Loading CrossView mapping from "+b+".");CrossViewJS.loadingMapping++;a.getJSON(b).success(function(b){a.extend(CrossViewJS.options.resources.viewModel,b.viewModel);a.extend(CrossViewJS.options.resources.view,b.view);CrossViewJS.view.loadTemplates()}).error(function(a,c){console.error("Failed to load View-Model class mapping from "+
b+".");throw c;}).complete(function(){0===--CrossViewJS.loadingMapping&&CrossViewJS.viewModel.requestBinding()})});a("link[rel='"+CrossViewJS.options.link.view+"']").each(function(){var b=a(this).attr("href"),e=a(this).attr(CrossViewJS.options.attributes.view.className);if(!e){var e=b,c=e.lastIndexOf("/");0<=c&&(e=e.substr(c+1));c=e.lastIndexOf(".");0<=c&&(e=e.substr(0,c))}console.log('Registering template for view "'+e+'" on '+b+".");CrossViewJS.options.resources.view[e]=b});a(CrossViewJS.view.loadTemplates)})})(jQuery);
(function(a){var b;function e(d,c){if((!b[d]||!b[d].url)&&CrossViewJS.options.resources.view[d]){console.log("Loading template "+d+" from "+CrossViewJS.options.resources.view[d]+".");b[d]={url:CrossViewJS.options.resources.view[d],loading:!0,callback:b[d]?b[d].callback||[]:[]};c&&b[d].callback.push(c);var e=a.extend(null,CrossViewJS.options.ajaxDefaults,{dataType:"text"});a.ajax(CrossViewJS.getAbsoluteURL(CrossViewJS.options.resources.view[d]),e).success(function(c){try{console.log("Template "+d+
" loaded from "+CrossViewJS.options.resources.view[d]+". ("+b[d].callback.length+" callback(s) waiting)"),CrossViewJS.template.setTemplate(d,c)}catch(e){CrossViewJS.notifyError(a("["+CrossViewJS.options.attributes.view.binding+"='"+d+"']"),"Can't compile template "+d+": "+e+"\n"+c);b[d]=null;return}for(b[d].loading=!1;b[d].callback.length;){c=b[d].callback.pop();try{c()}catch(h){h.stack?console.error(h.stack):console.error(h)}}}).error(function(a,c){console.error('Error loading template "'+d+'" from '+
CrossViewJS.options.resources.view[d]+": "+c+".");b[d]=null})}else if(b[d]&&c)b[d].loading?b[d].callback.push(c):c();else if(c){if(null==d)throw"Template undefined!";console.log("Needing template "+d+". Waiting for registration.");b[d]={callback:[c]}}}function c(a,c,b){try{CrossViewJS.clearError(c),e(a,function(){var e=CrossViewJS.template.render(a,b);c.html(e);c.attr(CrossViewJS.options.attributes.view.lastRendering,new Date);c.find("["+CrossViewJS.options.attributes.viewModel.binding+"]:not(["+
CrossViewJS.options.attributes.viewModel.bindId+"])").crossview("bindViewModel");c.find("["+CrossViewJS.options.attributes.view.binding+"]:not(["+CrossViewJS.options.attributes.view.lastRendering+"])").each(h);try{c.trigger("crossview-rendered")}catch(j){console.error('Error invoking "crossview-rendered" event for '+c.attr("id")+": "+j+"."),CrossViewJS.notifyError(c,j)}})}catch(j){console.error('Error rendering data using template "'+a+'": '+j),console.error(b),CrossViewJS.notifyError(c,j)}}function h(){var d=
a(this),b=d.attr(CrossViewJS.options.attributes.view.binding);e(b,function(){var a="true"==d.attr(CrossViewJS.options.attributes.view.withoutViewModel);if(!a&&d.crossview("shouldHaveViewModel"))console.log("Waiting view-model finish loading to render view "+d.attr("id")+".");else{var e=d.attr(CrossViewJS.options.attributes.fetch.jsonUrl),h=d.attr(CrossViewJS.options.attributes.fetch.jsonPath);if(e)if(d.hasClass(CrossViewJS.options.css.view.fetching))console.log("Ignoring render view "+d.attr("id")+
", since it is already fetching data.");else{var f=d.attr(CrossViewJS.options.attributes.fetch.fetchMode),e=CrossViewJS.getAbsoluteURL(e);console.log("Fetching JSON data from "+e+".");d.addClass(CrossViewJS.options.css.view.fetching);CrossViewJS.getJSON.call(d,e,null,f).success(function(l){console.log("Fetched JSON data from "+e+".");try{var f=d.crossview("getViewModel"),l=CrossViewJS.traverseJSON(l,h);!f||a?(console.log("Rendering "+d.attr("id")+" using "+b+" without a View-Model"),c(b,d,l)):(console.log("Rendering "+
d.attr("id")+" using "+b+" and its view-model "+f.instanceId+"."),f.setData(l),c(b,d,f.getRenderData()))}catch(p){CrossViewJS.notifyError(d,p)}}).complete(function(){d.removeClass(CrossViewJS.options.css.view.fetching)}).error(function(a,c){CrossViewJS.notifyError(d,"Cannot get JSON from "+e+": "+c||a)})}else if(f=d.crossview("getViewModel")){console.log("Rendering "+d.attr("id")+" using "+b+" and view-model "+f.instanceId);try{c(b,d,f.getRenderData())}catch(l){CrossViewJS.notifyError(d,l)}}else d.crossview("shouldHaveViewModel")||
console.error("Can't render "+d.attr("id")+" because there is no view-model instanciated.")}})}function f(){a("["+CrossViewJS.options.attributes.fetch.jsonUrl+"]:not(["+CrossViewJS.options.attributes.view.lastRendering+"]):not(."+CrossViewJS.options.css.view.fetching+")").each(h)}a.extend(!0,CrossViewJS,{options:{css:{view:{fetching:"crossview-fetching",loadingViewModel:"crossview-loading",error:"crossview-error"}},attributes:{view:{binding:"data-view",lastRendering:"data-view-rendered",withoutViewModel:"data-view-without-viewmodel",
className:"data-view-name"}},resources:{view:{}}},view:{}});b={};CrossViewJS.view.loadTemplates=function(){a("["+CrossViewJS.options.attributes.view.binding+"]:not(["+CrossViewJS.options.attributes.view.lastRendering+"])").each(function(){var c=a(this).attr(CrossViewJS.options.attributes.view.binding);e(c)})};CrossViewJS.fn.render=function(b,e){try{b?(e||(e=a(this).attr(CrossViewJS.options.attributes.view.binding)),c(e,a(this),b)):a(this).each(h)}catch(f){CrossViewJS.notifyError(a(this),f)}};CrossViewJS.requireTemplate=
e;a(f);a(window).ajaxComplete(function(){a(requestBinding);a(f)})})(jQuery);
(function(a){var b,e,c,h,f;function d(d,f){if(b[f]){console.log("Binding "+f+" to "+d.attr("id"));var j=new b[f],g=++e,k;for(k in c)j[k]||(j[k]=c[k]);a.extend(j,{instanceId:g,container:d});h[g]=j;d.attr(CrossViewJS.options.attributes.viewModel.bindId,g);a(function(){try{j.initialize(d,g),CrossViewJS.clearError(d)}catch(a){CrossViewJS.notifyError(d,a)}});d.attr(CrossViewJS.options.attributes.view.binding)?d.crossview("render"):(k=d.find("["+CrossViewJS.options.attributes.view.binding+"]:not(["+CrossViewJS.options.attributes.view.withoutViewModel+
"=true])"),console.log(k.length+" found. Rendering..."),k.removeClass(CrossViewJS.options.css.view.loadingViewModel).crossview("render"));try{0==g%CrossViewJS.options.viewModel.gbThreshold&&m()}catch(i){console.error("Can't run garbage collection: "+i)}return j}CrossViewJS.notifyError(d,"View-Model class not found: "+f+".")}function g(a){var c=a.attr(CrossViewJS.options.attributes.viewModel.bindId);if(!c&&!a.attr(CrossViewJS.options.attributes.viewModel.binding)){for(var d=a.parent();!c&&d.length&&
!(c=d.attr(CrossViewJS.options.attributes.viewModel.bindId),d.attr(CrossViewJS.options.attributes.viewModel.binding));d=d.parent());c&&a.attr(CrossViewJS.options.attributes.viewModel.bindId,c)}return c?h[c]:null}function i(a){var c=a.attr(CrossViewJS.options.attributes.viewModel.bindId),d=!1;if(!c&&!a.attr(CrossViewJS.options.attributes.viewModel.binding)){for(var b=a.parent();!c&&b.length;b=b.parent())if(c=b.attr(CrossViewJS.options.attributes.viewModel.bindId),b.attr(CrossViewJS.options.attributes.viewModel.binding)){d=
!0;break}c&&a.attr(CrossViewJS.options.attributes.viewModel.bindId,c)}else d=!0;return d&&!c}function j(){if(!f){f=!0;console.log("Finding view-model to bind...");try{a("["+CrossViewJS.options.attributes.viewModel.binding+"]:not(["+CrossViewJS.options.attributes.viewModel.bindId+"])").each(k)}finally{f=!1}}}function k(){if(!a(this).hasClass(CrossViewJS.options.attributes.viewModel.bindId))try{var c=a(this).attr(CrossViewJS.options.attributes.viewModel.binding);if(b[c])console.log('Binding View-Model "'+
c+'" to '+a(this).attr("id")),d(a(this),c);else if(CrossViewJS.options.resources.viewModel[c]){a(this).find("["+CrossViewJS.options.attributes.view.binding+"]").addClass(CrossViewJS.options.css.view.loadingViewModel);var e=a(this),f=a.extend(null,CrossViewJS.options.ajaxDefaults,{dataType:"script"}),h=CrossViewJS.options.resources.viewModel[c],g;"string"==typeof h?g=h:(g=h.href,f.scriptCharset=h.charset,console.log("Using "+f.scriptCharset+" charset for "+g+"."));g=CrossViewJS.getAbsoluteURL(g);console.log('Loading javascript for View-Model "'+
c+'" from '+g+".");a.ajax(g,f).success(function(){var a=CrossViewJS.traverseJSON(window,c);if(!a||a===window)throw"Undefined class "+c+", even after having loaded "+g;b[c]=a;j()}).error(function(a,d){CrossViewJS.options.resources.viewModel[c]=null;console.error('Error loading javascript for View-Model "'+c+'" from '+g+": "+d+".")}).complete(function(){e.find("."+CrossViewJS.options.css.view.loadingViewModel).each(function(){i(a(this))||a(this).removeClass(CrossViewJS.options.css.view.loadingViewModel)})})}else if(0===
CrossViewJS.loadingMapping){var m=CrossViewJS.traverseJSON(window,c);if(m&&m!==window)b[c]=m,j(),k.apply(this,arguments);else throw'View-Model class "'+c+'" not found!';}}catch(q){CrossViewJS.notifyError(a(this),q)}}function m(){var c=[];console.log("Running garbage collection from CrossViewJS.");for(var d=1;d<=e;d++)h[d]&&!a("["+CrossViewJS.options.attributes.viewModel.bindId+"="+d+"]").length?(console.log("Releasing view-model instance "+d+"."),h[d]=null,c.push(d)):h[d]||c.push(d);if(c.length>CrossViewJS.options.viewModel.compactThreshold)for(console.log("Compacting instances...");c.length;)d=
c.pop(),d!=e&&(console.log("Moving instance "+e+" to "+d+"."),h[d]=h[e],a("["+CrossViewJS.options.attributes.viewModel.bindId+"="+e+"]").attr(CrossViewJS.options.attributes.viewModel.bindId,d)),e--,h.pop()}e=0;h=[];b={$root:function(){return{getRenderData:function(){return this.data}}}};c={initialize:function(){},updateView:function(){this.container.attr(CrossViewJS.options.attributes.view.binding)?this.container.empty().crossview("render"):this.container.find("["+CrossViewJS.options.attributes.view.binding+
"]").empty().crossview("render")},updateClosestView:function(a){a.attr(CrossViewJS.options.attributes.view.binding)?a.empty().crossview("render"):a.parents("["+CrossViewJS.options.attributes.view.binding+"]:first").empty().crossview("render")},renderWithJSON:function(c){var d=c.attr(CrossViewJS.options.attributes.viewModel.renderTarget),b=a("#"+d);b.length?(b.empty().addClass(CrossViewJS.options.css.view.fetching),c.crossview("getJSON").success(function(a){console.log("Rendering "+d+" after command for rendering with JSON.");
b.crossview("render",a)}).complete(function(){b.removeClass(CrossViewJS.options.css.view.fetching)})):notifyError(c,"Target not found: "+d)},setData:function(a){this.data=a},getRenderData:function(){return this.data},getData:function(a){return a?this.data?this.data[a]:this.container.find("[name="+a+"]").val():this.data},getAncestorViewModel:function(){return g(this.container.parent())}};f=!1;a.extend(!0,CrossViewJS.options,{attributes:{viewModel:{bindId:"data-viewmodel-instance",binding:"data-viewmodel",
className:"data-viewmodel-name",renderTarget:"data-render"}},resources:{viewModel:{}},viewModel:{compactThreshold:10,gbThreshold:10},commands:c});a.extend(CrossViewJS.fn,{shouldHaveViewModel:function(){return i(this)},getViewModel:function(){return g(this)},bindViewModel:function(){this.each(k)},setViewModelData:function(c){this.each(function(){g(a(this)).setData(c)})}});a.extend(!0,CrossViewJS,{viewModel:{requestBinding:j,runGarbageCollection:m}});a(j)})(jQuery,jQuery.crossview);
(function(a){function b(){if(a.template&&a.render)CrossViewJS.template={setTemplate:function(b,c){a("<script id='crossview-template-"+b+"' type='text/x-jquery-tmpl'>"+c+"<\/script>").template(b)},render:a.render};else if(a.template&&!a.render&&a.tmpl)CrossViewJS.template={setTemplate:a.template,render:a.tmpl}}CrossViewJS.template=null;a(function(){b();CrossViewJS.template||setTimeout(b,150)})})(jQuery);
(function(a){a.extend(!0,CrossViewJS.options,{attributes:{fetch:{jsonPath:"data-json-path",jsonUrl:"data-json-url",fetchMode:"data-fetch-mode",xpath:"data-fetch-xpath"}}});CrossViewJS.fn.getJSON=function(b,e,c){var h=a(this),f=h.attr(CrossViewJS.options.attributes.fetch.fetchMode);b||(b=h.attr(CrossViewJS.options.attributes.fetch.jsonUrl));c||(c=h.attr(CrossViewJS.options.attributes.fetch.jsonPath));return CrossViewJS.getJSON.call(this,b,e,f,c)};CrossViewJS.getJSON=function(b,e,c,h){var f=null,d=
null,g=null;c||(c="default");var e=a.extend(null,CrossViewJS.options.ajaxDefaults,{dataType:"json"},e),b=CrossViewJS.getAbsoluteURL(b),i={"default":{getResultJSON:function(a){return a},transformURL:function(a){return a}},"yql-xml":{getResultJSON:function(a){return a.query.results},transformURL:function(a,c){if(c&&c.data){var d=!0;0>a.indexOf("?")&&(a+="?");for(var b in c.data)c.data[b]&&(d?d=!1:a+="&",a+=encodeURIComponent(b)+"="+encodeURIComponent(c.data[b]));c.data=null}return"http://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20xml%20where%20url%3D%22"+
encodeURIComponent(a)+"%22"}},yql:{getResultJSON:function(a){return a.query.results.json},transformURL:function(a,c){if(c&&c.data){var d=!0;0>a.indexOf("?")&&(a+="?");for(var b in c.data)c.data[b]&&(d?d=!1:a+="&",a+=encodeURIComponent(b)+"="+encodeURIComponent(c.data[b]));c.data=null}return"http://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20json%20where%20url%3D%22"+encodeURIComponent(a)+"%22"}},"yql-html":{getResultJSON:function(a){return a.query.results},transformURL:function(c,
d){if(d&&d.data){var b=!0;0>c.indexOf("?")&&(c+="?");for(var e in d.data)d.data[e]&&(b?b=!1:c+="&",c+=encodeURIComponent(e)+"="+encodeURIComponent(d.data[e]));d.data=null}b=a(this).attr(CrossViewJS.options.attributes.fetch.xpath);if(!b)throw CrossViewJS.options.attributes.fetch.xpath+" attribute is mandatory for yql-html mode.";return"http://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20html%20where%20url%3D%22"+encodeURIComponent(c)+"%22%20and%20xpath=%22"+encodeURIComponent(b)+
"%22"}}}[c];if(!i)throw"Unknown mode "+c+".";b=i.transformURL.call(this,b,e);a.ajax(b,e).complete(function(){f&&f(arguments)}).error(function(){d&&d(arguments)}).success(function(a){a=i.getResultJSON.call(this,a,e);h&&(a=CrossViewJS.traverseJSON(a,h));g(a,Array.prototype.slice.call(arguments,1))});return{complete:function(a){f=a;return this},error:function(a){d=a;return this},success:function(a){g=a;return this}}}})(jQuery);
(function(a){function b(){var b=a(this),e=b.attr(CrossViewJS.options.attributes.beforeCommandSubmission);if(e&&!1===c(b,e))return!1;var d=b.attr(CrossViewJS.options.attributes.command),e=b.attr(CrossViewJS.options.attributes.form.render);return d||e?(CrossViewJS.form.submit(b,function(a){d&&c(b,d,[a])}),!1):!0}function e(){for(var b=a(this),e=b.attr(CrossViewJS.options.attributes.command),e=[b,e],d=0;d<arguments.length;d++)e.push(arguments[d]);return!1!==c.apply(b,e)}function c(a,c,d){var b=a.crossview("getViewModel");
for(console.log('Executing command "'+c+'".');b&&!b[c];)b=b.getAncestorViewModel();if(b||CrossViewJS.options.commands[c]){a=[a];if(d)for(var e=0;e<d.length;e++)a.push(d[e]);return b?b[c].apply(b,a):CrossViewJS.options.commands[c].apply(null,a)}CrossViewJS.notifyError(a,"Command not found: "+c+".")}a.extend(CrossViewJS.options.attributes,{command:"data-command",beforeCommandSubmission:"data-command-before-submission"});a(function(){a("a["+CrossViewJS.options.attributes.command+"]").live("click",e);
a("button["+CrossViewJS.options.attributes.command+"]").live("click",e);a("form").live("submit",b)});a.extend(CrossViewJS.fn,{command:function(b){for(var e=[],d=1;d<e.length;d++)e.push(arguments[d]);a(this).each(function(){c(a(this),b,e)})}})})(jQuery);
(function(a){function b(c,b){for(var f=c.attr(CrossViewJS.options.attributes.form.render),d=f?f.split(","):[],g=[],i=0;i<d.length;i++){g[i]={id:d[i],el:a("#"+a.trim(d[i]))};g[i].view=c.attr(CrossViewJS.options.attributes.view.className)||g[i].el.attr(CrossViewJS.options.attributes.view.binding);if(!g[i].el.length)return CrossViewJS.notifyError(c,"Target element not found: "+d[i]+"."),!1;if(!g[i].view)return CrossViewJS.notifyError(g[i].el,'Undefined view for target element "'+d[i]+'".'),!1;CrossViewJS.requireTemplate(g[i].view)}try{var j=
c.attr(CrossViewJS.options.attributes.fetch.fetchMode),k=c.attr("action"),m=c.attr("method"),l=c.serializeObject(),n=c.attr(CrossViewJS.options.attributes.form.renderMode)||CrossViewJS.options.form.defaultRenderMode;if(f&&!e[n])return CrossViewJS.notifyError(c,"Unknown render mode: "+n+"."),!1;f?a(g).each(function(){this.el.addClass(CrossViewJS.options.css.view.fetching)}):c.crossview("getViewModel").container.addClass(CrossViewJS.options.css.view.fetching);console.log("Submitting form to "+k);CrossViewJS.getJSON.call(c,
k,{type:m,data:l},j).success(function(d){d?console.log("Data received from "+k):console.log("No data received from "+k);try{var i=c.attr(CrossViewJS.options.attributes.fetch.jsonPath);i&&(d=CrossViewJS.traverseJSON(d,i));try{f?a(g).each(function(){try{var b={form:c,target:this.el,targetId:this.id,targetView:this.view,jsonArgs:l};if("true"==this.el.attr(CrossViewJS.options.attributes.view.withoutViewModel))b.data=d;else{var f=this.el.crossview("getViewModel");f?(f.getData()!=d&&f.setData(d),b.data=
f.getRenderData()):b.data=d}CrossViewJS.requireTemplate(this.view,function(){b.target.removeClass(CrossViewJS.options.css.view.fetching);e[n].apply(c,[b])})}catch(h){a(g).each(function(){b.target.removeClass(CrossViewJS.options.css.view.fetching);CrossViewJS.notifyError(this.el,h)})}}):c.crossview("getViewModel").container.removeClass(CrossViewJS.options.css.view.fetching)}finally{b&&b(d)}}catch(j){a(g).each(function(){CrossViewJS.notifyError(this.el,j)})}}).error(function(b,d){CrossViewJS.notifyError(c,
d);f?a(g).each(function(){renderData.target.removeClass(CrossViewJS.options.css.view.fetching);CrossViewJS.notifyError(this.el,d)}):c.crossview("getViewModel").container.removeClass(CrossViewJS.options.css.view.fetching)})}catch(o){a(g).each(function(){CrossViewJS.notifyError(this.el,o)})}}var e={};a.extend(!0,CrossViewJS,{options:{attributes:{form:{render:"data-form-render",renderMode:"data-form-render-mode"}},form:{defaultRenderMode:"view-model"},commands:{submit:b}},form:{}});CrossViewJS.form.registerRenderMode=
function(a,b){e[a]=b};CrossViewJS.form.registerRenderMode("append",function(c){var b=c.target.attr(CrossViewJS.options.attributes.fetch.jsonPath),e=a("<div/>"),d;for(d in CrossViewJS.options.attributes.view){var g=c.target.attr(CrossViewJS.options.attributes.view[d]);g&&e.attr(CrossViewJS.options.attributes.view[d],g)}b=CrossViewJS.traverseJSON(c.data,b);e.crossview("render",b,c.targetView);1<e.children().length?c.target.append(e):(e.children().attr(CrossViewJS.options.attributes.view.lastRendering,
e.attr(CrossViewJS.options.attributes.view.lastRendering)),c.target.append(e.children()),e.remove())});CrossViewJS.form.registerRenderMode("replace",function(a){var b=a.target.attr(CrossViewJS.options.attributes.fetch.jsonPath),b=CrossViewJS.traverseJSON(a.data,b);a.target.crossview("render",b,a.targetView)});CrossViewJS.form.registerRenderMode("view-model",function(a){var b;(b=a.target.crossview("getViewModel"))||(b=setViewModel(a.target,"$root"));b.setData(a.data);a.target.crossview("render")});
CrossViewJS.form.submit=b})(jQuery);
(function(a){a(function(){a.mobile&&a("["+CrossViewJS.options.attributes.view.binding+"]").live("crossview-rendered",function(){var b=a(this);try{var e=a(a.mobile.activePage),c=e.get(0)===b.get(0)||e.has(b);if(c||b.parents("[role=main]"))if(console.log("Invoking jQuery Mobile bindings on "+b.attr("id")+"."),b.removeData(),c||(e=b.parents("[data-role=page]")),e.data("page"))try{e.trigger("pagecreate")}catch(h){e.page()}else e.page()}catch(f){console.log("Error invoking pagecreate for $.mobile: "+f+
".")}})})})(jQuery);